In [18]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [19]:
reviews = [
    'nice food',
    'amazing restaurant',
    'too good',
    'just loved it!',
    'will go again',
    'horrible food',
    'never go there',
    'poor service',
    'poor quality',
    'needs improvement'
]
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [20]:
one_hot("amazing restaurant",50)

[14, 4]

In [21]:
vocab_size = 50
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[37, 27], [14, 4], [32, 17], [21, 37, 37], [36, 31, 37], [26, 27], [14, 31, 34], [36, 14], [36, 29], [26, 2]]


In [22]:
max_len = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_len, padding='post')
padded_reviews

array([[37, 27,  0],
       [14,  4,  0],
       [32, 17,  0],
       [21, 37, 37],
       [36, 31, 37],
       [26, 27,  0],
       [14, 31, 34],
       [36, 14,  0],
       [36, 29,  0],
       [26,  2,  0]], dtype=int32)

In [23]:
embedded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length=max_len, name="embedding"))
model.add(Flatten())
model.add(Dense(1,activation = 'sigmoid'))

In [24]:
X = padded_reviews
y = sentiment

In [25]:
model.compile(optimizer = 'adam',loss='binary_crossentropy', metrics = ['accuracy'])

In [26]:
model.build(input_shape=(None, max_len))

In [27]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 3, 4)           │           200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 12)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            13 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 213 (852.00 B)

 Trainable params: 213 (852.00 B)

 Non-trainable params: 0 (0.00 B)

In [28]:
model.fit(X, y, epochs=50, verbose=0)

In [29]:
model.evaluate(X,y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 337ms/step - accuracy: 1.0000 - loss: 0.6274


[0.6273508667945862, 1.0]

In [30]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

50

In [31]:
weights[37]

array([-0.00213103,  0.12704135,  0.0980764 , -0.00539938], dtype=float32)

In [32]:
weights[14]

array([ 0.04163576, -0.0058027 ,  0.00256722, -0.02042479], dtype=float32)